### ISSUE TITLE
how to run this project in jenkins

### ISSUE THREAD

**Issue by dharmatejadevops** [pmav/game-of-life#8]
when i run with commnad npm run ci-test it getting bellow error

+ npm -version
3.5.2
+ npm run ci-test
npm ERR! Linux 4.15.0-1035-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "ci-test"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /home/jenkins/workspace/gameoflife_js/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/jenkins/workspace/gameoflife_js/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/jenkins/workspace/gameoflife_js/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jenkins/workspace/gameoflife_js/npm-debug.log
+ :
+ npm run ci-lint
npm ERR! Linux 4.15.0-1035-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "ci-lint"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /home/jenkins/workspace/gameoflife_js/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/jenkins/workspace/gameoflife_js/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/jenkins/workspace/gameoflife_js/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jenkins/workspace/gameoflife_js/npm-debug.log
+ :
Finished: SUCCESS

**Comment by pmav** [comment]
This project doesn't have a package.json - there is no npm support.

**Comment by dharmatejadevops** [comment]
then how to run this project on jenkins  & which tool we use for running on
jenkins

Thanks & Regards

*Dharmateja*
email:*dharmateja.veeramani@gmail.com <dharmateja.veeramani@gmail.com>*
cell:+91 9000668797.

**Comment by pmav** [comment]
To run this project just open the index.html using the browser. There is nothing to compile, pack, etc.
